// example-f4se-plugin/src/main.cpp
//
// Demonstrates PrismaUI_F4 integration using NewCommonLib (xmake-based CommonLibF4):
//   - F4SE_PLUGIN_VERSION / F4SE_PLUGIN_LOAD macros replace F4SEPlugin_Query.
//   - F4SE::Init() sets up logging automatically — no manual spdlog setup needed.
//   - REX::INFO / REX::WARN / REX::CRITICAL replace logger::info / logger::warn.
//   - All other PrismaUI_F4 API usage is unchanged.
#include "PCH.h"
#include "PrismaUI_F4_API.h"
#include "PrismaUI_F4_Helper.h"
#include "keyhandler/keyhandler.h"

static PRISMA_UI_API::IVPrismaUI4* g_api  = nullptr;
static PrismaView                   g_view = 0;
static bool                         g_visible = false;

static void OnDomReady(PrismaView v)
{
    // DOM is ready — register listeners and push initial state.
    // BindUIEvent callbacks fire on the game thread — RE:: access is safe directly.
    // RegisterJSListener callbacks fire on the Ultralight render thread — use AddTask for RE::.
    // window.prisma is already injected by PrismaUI_F4 before this callback fires.

    g_api->RegisterConsoleCallback(v, [](PrismaView, PRISMA_UI_API::ConsoleMessageLevel lvl, const char* msg) {
        switch (lvl) {
        case PRISMA_UI_API::ConsoleMessageLevel::Error:   REX::CRITICAL("[JS] {}", msg); break;
        case PRISMA_UI_API::ConsoleMessageLevel::Warning: REX::WARN("[JS] {}",  msg); break;
        default:                                          REX::INFO("[JS] {}",  msg); break;
        }
    });

    // BindUIEvent — fires on the game thread. RE:: access works directly inside the callback.
    g_api->BindUIEvent(v, "requestClose", [](const char*) {
        g_visible = false;
        g_api->Unfocus(g_view);
        g_api->Hide(g_view);
    });

    // Receives JSON from JS: { "message": "..." }
    // GetJsonString parses the value without pulling in a full JSON library.
    g_api->BindUIEvent(v, "sendDataToF4SE", [](const char* data) {
        std::string msg = PRISMA_UI_HELPER::GetJsonString(data ? data : "", "message");
        REX::INFO("Received from JS: {}", msg);

        // RE:: access is safe here — already on game thread.
        // Example: read player health
        // auto* player = RE::PlayerCharacter::GetSingleton();
        // float hp = player->GetActorValue(*RE::ActorValue::GetSingleton()->health);

        // Example: fire a Papyrus custom event on a quest form (see PrismaUI_F4_Helper.h).
        // Requires a CustomEvent declared in a Papyrus script attached to the form.
        // auto* form = RE::TESForm::GetFormByID(0x12345);
        // PRISMA_UI_HELPER::SendPapyrusEvent(form, "OnDataReceived");
    });

    g_api->Invoke(v, "init()");
    REX::INFO("View DOM ready: {}", v);
}

static void CreateViews()
{
    if (!g_api || (g_view != 0 && g_api->IsValid(g_view))) return;

    g_view = g_api->CreateView("PrismaUI-F4-Example/index.html", OnDomReady);
    // Views start hidden — show explicitly on toggle.
}

static void Toggle()
{
    if (!g_api || !g_api->IsValid(g_view)) return;
    g_visible = !g_visible;
    if (g_visible) {
        g_api->Show(g_view);
        g_api->Focus(g_view, /*pauseGame=*/false);
        g_api->Invoke(g_view, "updateFocusLabel('Focused. Press F3 to close.')");
    } else {
        g_api->Unfocus(g_view);
        g_api->Hide(g_view);
    }
}

static void F4SEMessageHandler(F4SE::MessagingInterface::Message* message)
{
    switch (message->type) {

    case F4SE::MessagingInterface::kGameDataReady:
    {
        g_api = PRISMA_UI_API::RequestPluginAPI<PRISMA_UI_API::IVPrismaUI4>();
        if (!g_api) {
            REX::CRITICAL("PrismaUI_F4 API not found — is PrismaUI_F4.dll installed?");
            return;
        }

        KeyHandler::RegisterSink();
        [[maybe_unused]] auto _ = KeyHandler::GetSingleton()->Register(
            static_cast<uint32_t>(RE::BS_BUTTON_CODE::kF3), KeyEventType::KEY_DOWN, Toggle);
        break;
    }

    case F4SE::MessagingInterface::kPostLoadGame:
    case F4SE::MessagingInterface::kNewGame:
        if (g_api) CreateViews();
        break;

    default:
        break;
    }
}

// NewCommonLib pattern: F4SE_PLUGIN_LOAD replaces the old F4SEPlugin_Query + F4SEPlugin_Load pair.
// F4SE_PLUGIN_VERSION is generated by the commonlibf4.plugin xmake rule from xmake.lua metadata.
// F4SE::Init() automatically creates the log file at:
//   %USERPROFILE%\Documents\My Games\Fallout4\F4SE\PrismaUI-F4-Example-Plugin.log
F4SE_PLUGIN_LOAD(const F4SE::LoadInterface* a_intfc)
{
    F4SE::Init(a_intfc);
    F4SE::GetMessagingInterface()->RegisterListener(F4SEMessageHandler);
    return true;
}
