// example-f4se-plugin/src/main.cpp
//
// Demonstrates PrismaUI_F4 integration using NewCommonLib (xmake-based CommonLibF4):
//   - F4SE_PLUGIN_QUERY exported for F4SE OG (0.6.x) compatibility.
//   - F4SE_PLUGIN_VERSION auto-generated by commonlibf4.plugin rule for F4SE NG (0.7.x).
//   - F4SE::Init() sets up logging automatically — no manual spdlog setup needed.
//   - REX::INFO / REX::WARN / REX::CRITICAL replace logger::info / logger::warn.
#include "PCH.h"
#include "PrismaUI_F4_API.h"
#include "PrismaUI_F4_Helper.h"
#include "keyhandler/keyhandler.h"

static PRISMA_UI_API::IVPrismaUI4* g_api  = nullptr;
static PrismaView                   g_view = 0;
static bool                         g_visible = false;

static void OnDomReady(PrismaView v)
{
    // DOM is ready — register listeners and push initial state.
    // BindUIEvent callbacks fire on the game thread — RE:: access is safe directly.
    // RegisterJSListener callbacks fire on the Ultralight render thread — use AddTask for RE::.
    // window.prisma is already injected by PrismaUI_F4 before this callback fires.

    g_api->RegisterConsoleCallback(v, [](PrismaView, PRISMA_UI_API::ConsoleMessageLevel lvl, const char* msg) {
        switch (lvl) {
        case PRISMA_UI_API::ConsoleMessageLevel::Error:   REX::CRITICAL("[JS] {}", msg); break;
        case PRISMA_UI_API::ConsoleMessageLevel::Warning: REX::WARN("[JS] {}",  msg); break;
        default:                                          REX::INFO("[JS] {}",  msg); break;
        }
    });

    g_api->BindUIEvent(v, "requestClose", [](const char*) {
        g_visible = false;
        g_api->Unfocus(g_view);
        g_api->Hide(g_view);
    });

    g_api->BindUIEvent(v, "sendDataToF4SE", [](const char* data) {
        std::string msg = PRISMA_UI_HELPER::GetJsonString(data ? data : "", "message");
        REX::INFO("Received from JS: {}", msg);
    });

    g_api->Invoke(v, "init()");
    REX::INFO("View DOM ready: {}", v);
}

static void CreateViews()
{
    if (!g_api || (g_view != 0 && g_api->IsValid(g_view))) return;
    g_view = g_api->CreateView("PrismaUI-F4-Example/index.html", OnDomReady);
}

static void Toggle()
{
    if (!g_api || !g_api->IsValid(g_view)) return;
    g_visible = !g_visible;
    if (g_visible) {
        g_api->Show(g_view);
        g_api->Focus(g_view, /*pauseGame=*/false);
        g_api->Invoke(g_view, "updateFocusLabel('Focused. Press F3 to close.')");
    } else {
        g_api->Unfocus(g_view);
        g_api->Hide(g_view);
    }
}

static void F4SEMessageHandler(F4SE::MessagingInterface::Message* message)
{
    switch (message->type) {

    case F4SE::MessagingInterface::kGameDataReady:
    {
        g_api = PRISMA_UI_API::RequestPluginAPI<PRISMA_UI_API::IVPrismaUI4>();
        if (!g_api) {
            REX::CRITICAL("PrismaUI_F4 API not found — is PrismaUI_F4.dll installed?");
            return;
        }
        KeyHandler::RegisterSink();
        [[maybe_unused]] auto _ = KeyHandler::GetSingleton()->Register(
            static_cast<uint32_t>(RE::BS_BUTTON_CODE::kF3), KeyEventType::KEY_DOWN, Toggle);
        break;
    }

    case F4SE::MessagingInterface::kPostLoadGame:
    case F4SE::MessagingInterface::kNewGame:
        if (g_api) CreateViews();
        break;

    default:
        break;
    }
}

// F4SE OG (0.6.x) requires F4SEPlugin_Query to recognise a plugin.
// F4SE NG (0.7.x) uses F4SEPlugin_Version (auto-generated by commonlibf4.plugin rule).
// Both exported so the DLL loads on either runtime.
extern "C" DLLEXPORT bool F4SEAPI F4SEPlugin_Query(const F4SE::QueryInterface* a_f4se, F4SE::PluginInfo* a_info)
{
    a_info->infoVersion = F4SE::PluginInfo::kVersion;
    a_info->name        = "PrismaUI-F4-Example-Plugin";
    a_info->version     = 1;
    if (a_f4se->IsEditor()) return false;
    if (a_f4se->RuntimeVersion() < F4SE::RUNTIME_1_10_162) return false;
    return true;
}

F4SE_PLUGIN_LOAD(const F4SE::LoadInterface* a_intfc)
{
    F4SE::Init(a_intfc);
    F4SE::GetMessagingInterface()->RegisterListener(F4SEMessageHandler);
    return true;
}
