#include "API/API.h"
#include "Hooks/Hooks.h"
#include "Utils/DllLoader.h"

static void F4SEMessageHandler(F4SE::MessagingInterface::Message* message)
{
    if (message->type == F4SE::MessagingInterface::kGameDataReady) {
        Hooks::D3DHooks::Install();
    }
}

// F4SE_PLUGIN_VERSION is auto-generated by the commonlibf4.plugin xmake rule
// from the name/author/version declared in xmake.lua. No F4SEPlugin_Query needed.
// F4SE::Init() creates the log file automatically at:
//   %USERPROFILE%\Documents\My Games\Fallout4\F4SE\PrismaUI_F4.log
F4SE_PLUGIN_LOAD(const F4SE::LoadInterface* a_intfc)
{
    F4SE::Init(a_intfc, F4SE::InitInfo{
        .logName       = "PrismaUI_F4",
        .trampoline    = true,
        .trampolineSize = 1 << 10
    });

    if (!PrismaUI::Utils::DllLoader::GetSingleton().LoadUltralightLibraries()) {
        logger::critical("Failed to load Ultralight libraries from Data/PrismaUI_F4/libs/!");
        return false;
    }

    const auto* messaging = F4SE::GetMessagingInterface();
    if (!messaging) {
        logger::critical("Failed to get F4SE messaging interface!");
        return false;
    }
    messaging->RegisterListener(F4SEMessageHandler);

    return true;
}

extern "C" DLLEXPORT void* F4SEAPI RequestPluginAPI(const PRISMA_UI_API::InterfaceVersion a_interfaceVersion)
{
    auto api = PluginAPI::PrismaUIInterface::GetSingleton();

    switch (a_interfaceVersion) {
    case PRISMA_UI_API::InterfaceVersion::V1:
        logger::info("RequestPluginAPI returned V1 interface");
        return static_cast<PRISMA_UI_API::IVPrismaUI1*>(api);
    case PRISMA_UI_API::InterfaceVersion::V2:
        logger::info("RequestPluginAPI returned V2 interface");
        return static_cast<PRISMA_UI_API::IVPrismaUI2*>(api);
    case PRISMA_UI_API::InterfaceVersion::V3:
        logger::info("RequestPluginAPI returned V3 interface");
        return static_cast<PRISMA_UI_API::IVPrismaUI3*>(api);
    case PRISMA_UI_API::InterfaceVersion::V4:
        logger::info("RequestPluginAPI returned V4 interface");
        return static_cast<PRISMA_UI_API::IVPrismaUI4*>(api);
    default:
        logger::info("RequestPluginAPI: unsupported interface version");
        return nullptr;
    }
}
