#include "API/API.h"
#include "Hooks/Hooks.h"
#include "Utils/DllLoader.h"
#include "PrismaUI/NotificationSystem.h"
#include <tlhelp32.h>

static bool g_overlayDetected = false;
static bool g_pluginDisabled = false;
static std::string g_detectedOverlayName;

namespace {
    bool IsConflictingOverlayRunning() {
        const char* conflicting_procs[] = {
            "RTSS.exe",              // RivaTuner Statistics Server
            "RTSSHooked.exe",        // RivaTuner hooked version
            "RTSSHooksLoader64.exe", // RivaTuner background loader (even when window closed)
            "MSIAfterburner.exe",    // MSI Afterburner
            "OverdriveNTool.exe",    // AMD Overdrive
        };

        const char* friendly_names[] = {
            "RivaTuner Statistics Server (RTSS.exe)",
            "RivaTuner (RTSSHooked.exe)",
            "RivaTuner Loader (RTSSHooksLoader64.exe) - close from system tray",
            "MSI Afterburner (MSIAfterburner.exe)",
            "AMD Overdrive (OverdriveNTool.exe)",
        };

        HANDLE snapshot = CreateToolhelp32Snapshot(TH32CS_SNAPPROCESS, 0);
        if (snapshot == INVALID_HANDLE_VALUE) return false;

        PROCESSENTRY32 entry{};
        entry.dwSize = sizeof(PROCESSENTRY32);

        if (Process32First(snapshot, &entry)) {
            do {
                for (size_t i = 0; i < 5; ++i) {
                    if (_stricmp(entry.szExeFile, conflicting_procs[i]) == 0) {
                        logger::warn("[PrismaUI Overlay Detection] Found: {}", entry.szExeFile);
                        g_detectedOverlayName = friendly_names[i];
                        CloseHandle(snapshot);
                        return true;
                    }
                }
            } while (Process32Next(snapshot, &entry));
        }

        CloseHandle(snapshot);
        return false;
    }

    void NotifyUserOverlayDetected() {
        std::string message = "PrismaUI cannot run with this software active.\n\n";
        message += "Detected: " + g_detectedOverlayName + "\n\n";
        message += "This GPU monitoring software conflicts with Ultralight rendering.\n\n";
        message += "To play:\n";
        message += "1. Close " + g_detectedOverlayName + "\n";
        message += "2. Restart Fallout 4\n\n";
        message += "Fallout 4 will now close.";

        MessageBoxA(
            nullptr,
            message.c_str(),
            "PrismaUI - Overlay Conflict",
            MB_OK | MB_ICONWARNING
        );

        // Kill the game process - user must close overlay and restart
        std::exit(1);
    }
}

static void F4SEMessageHandler(F4SE::MessagingInterface::Message* message)
{
    if (message->type == F4SE::MessagingInterface::kGameDataReady) {
        Hooks::D3DHooks::Install();
    }
}

// F4SE_PLUGIN_VERSION is auto-generated by the commonlibf4.plugin xmake rule
// from the name/author/version declared in xmake.lua. No F4SEPlugin_Query needed.
// F4SE::Init() creates the log file automatically at:
//   %USERPROFILE%\Documents\My Games\Fallout4\F4SE\PrismaUI_F4.log
F4SE_PLUGIN_LOAD(const F4SE::LoadInterface* a_intfc)
{
    F4SE::Init(a_intfc, F4SE::InitInfo{
        .logName       = "PrismaUI_F4",
        .trampoline    = true,
        .trampolineSize = 1 << 10
    });

    // Check for conflicting overlay software IMMEDIATELY - before game launches
    g_overlayDetected = IsConflictingOverlayRunning();
    if (g_overlayDetected) {
        logger::warn("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━");
        logger::warn("[PrismaUI] Overlay detected - exiting before game launch");
        logger::warn("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━");
        logger::warn("Detected: {}", g_detectedOverlayName);
        logger::warn("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━");

        // Show alert popup and exit IMMEDIATELY - before game window opens, before intro
        NotifyUserOverlayDetected();
        // Function calls exit(1), never returns here
    }

    // Register message handler for normal operation (no overlay detected)
    const auto* messaging = F4SE::GetMessagingInterface();
    if (!messaging) {
        logger::critical("Failed to get F4SE messaging interface!");
        return false;
    }
    messaging->RegisterListener(F4SEMessageHandler);

    if (!PrismaUI::Utils::DllLoader::GetSingleton().LoadUltralightLibraries()) {
        logger::critical("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━");
        logger::critical("[PrismaUI CRITICAL] Failed to load Ultralight libraries!");
        logger::critical("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━");
        logger::critical("Required files missing from: Data/PrismaUI_F4/libs/");
        logger::critical("");
        logger::critical("Expected files:");
        logger::critical("  • AppCore.dll");
        logger::critical("  • Ultralight.dll");
        logger::critical("  • UltralightCore.dll");
        logger::critical("  • WebCore.dll");
        logger::critical("");
        logger::critical("Also check: Data/PrismaUI_F4/resources/");
        logger::critical("  • cacert.pem");
        logger::critical("  • icudt67l.dat");
        logger::critical("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━");
        return false;
    }

    return true;
}

extern "C" DLLEXPORT void* F4SEAPI RequestPluginAPI(const PRISMA_UI_API::InterfaceVersion a_interfaceVersion)
{
    if (g_pluginDisabled) {
        logger::warn("RequestPluginAPI: PrismaUI is disabled (GPU overlay detected)");
        return nullptr;
    }

    auto api = PluginAPI::PrismaUIInterface::GetSingleton();

    switch (a_interfaceVersion) {
    case PRISMA_UI_API::InterfaceVersion::V1:
        logger::info("RequestPluginAPI returned V1 interface");
        return static_cast<PRISMA_UI_API::IVPrismaUI1*>(api);
    case PRISMA_UI_API::InterfaceVersion::V2:
        logger::info("RequestPluginAPI returned V2 interface");
        return static_cast<PRISMA_UI_API::IVPrismaUI2*>(api);
    case PRISMA_UI_API::InterfaceVersion::V3:
        logger::info("RequestPluginAPI returned V3 interface");
        return static_cast<PRISMA_UI_API::IVPrismaUI3*>(api);
    case PRISMA_UI_API::InterfaceVersion::V4:
        logger::info("RequestPluginAPI returned V4 interface");
        return static_cast<PRISMA_UI_API::IVPrismaUI4*>(api);
    default:
        logger::info("RequestPluginAPI: unsupported interface version");
        return nullptr;
    }
}
